### ISSUE TITLE
error trying to run the backend - node_modules out of sync

### ISSUE THREAD

**Issue by tansaku** [Human-Connection/Nitro-Backend#143] opened 2019-02-04 12:43 UTC
**Bug Description**
Switching to new version of node and the latest version of the code I got this:
```
→ yarn run dev
yarn run v1.13.0
$ nodemon --exec babel-node src/
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/`
/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/graphql-yoga/node_modules/graphql-tools/dist/generate/addResolveFunctionsToSchema.js:73
                throw new _1.SchemaError(typeName + " was defined in resolvers, but it's not an object");
                ^

Error: Mutation was defined in resolvers, but it's not an object
[nodemon] app crashed - waiting for file changes before starting...
```

**To Reproduce**
Not sure - `yarn install` on node 9.5 and then again on node 9.10

**Expected behavior**
Should work

**Additional context**
Can fix with `rm -rf node_modules`

**Comment by appinteractive** [comment] 2019-02-04 13:19
We require node 10 LTS.

**Comment by tansaku** [comment] 2019-02-04 21:00
interesting that you say that @appinteractive - when I installed I got this:

```
→ yarn install
yarn install v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error eslint@5.12.1: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0". Got "9.5.0"
```

**Comment by appinteractive** [comment] 2019-02-04 21:15
We should add the version back again to 10.x. The issue you are mentioning is more due to your node change, and not a bug in the application. At least that’s what I understand from the “reproduction” part in the description as you have switched node versions in between  right?

**Comment by appinteractive** [comment] 2019-02-07 11:26
Maybe you could add it as a troubleshooting part to our documentation?

**Comment by tansaku** [comment] 2019-02-07 13:53
that's a good idea @appinteractive

**Comment by roschaefer** [comment] 2019-03-21 22:05
@tansaku closing this for now. Check out or new [monorepo](https://github.com/Human-Connection/Human-Connection), many things including dependencies have changed.

**Closed by roschaefer** 2019-03-21 22:05 UTC
